# Generated by Django 4.2.1 on 2023-05-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_registration_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
