# Generated by Django 4.2 on 2023-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userdnssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdnssi',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdnssi',
            name='entite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdnssi',
            name='evaluationRecente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdnssi',
            name='numero',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
