# Generated by Django 4.2 on 2023-06-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userdnssi_email_userdnssi_entite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdnssi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdnssi',
            name='entite',
        ),
        migrations.RemoveField(
            model_name='userdnssi',
            name='evaluationRecente',
        ),
        migrations.RemoveField(
            model_name='userdnssi',
            name='numero',
        ),
    ]
