# Generated by Django 4.2.1 on 2023-05-22 04:34

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(default='body'),
        ),
    ]
