# Generated by Django 4.2.1 on 2023-05-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_yourmodel_remove_blog_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='Video',
        ),
    ]
