# Generated by Django 4.2.1 on 2023-05-22 05:08

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_rename_yourmodel_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='youtube.com'),
        ),
    ]
