# Generated by Django 4.2.1 on 2023-05-22 05:30

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_delete_video_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
