# Generated by Django 4.2 on 2023-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('objectif1', models.CharField(max_length=100)),
                ('objectif2', models.CharField(max_length=100)),
                ('objectif3', models.CharField(max_length=100)),
                ('objectif4', models.CharField(max_length=100)),
                ('objectif5', models.CharField(max_length=100)),
                ('objectif6', models.CharField(max_length=100)),
                ('objectif7', models.CharField(max_length=100)),
                ('objectif8', models.CharField(max_length=100)),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('question4', models.CharField(max_length=100)),
                ('question5', models.CharField(max_length=100)),
                ('question6', models.CharField(max_length=100)),
                ('question7', models.CharField(max_length=100)),
                ('question8', models.CharField(max_length=100)),
                ('question9', models.CharField(max_length=100)),
                ('question10', models.CharField(max_length=100)),
                ('question11', models.CharField(max_length=100)),
                ('question12', models.CharField(max_length=100)),
                ('question13', models.CharField(max_length=100)),
                ('question15', models.CharField(max_length=100)),
                ('question16', models.CharField(max_length=100)),
                ('question17', models.CharField(max_length=100)),
                ('question18', models.CharField(max_length=100)),
                ('question19', models.CharField(max_length=100)),
                ('question20', models.CharField(max_length=100)),
                ('question21', models.CharField(max_length=100)),
                ('question22', models.CharField(max_length=100)),
                ('question23', models.CharField(max_length=100)),
                ('question24', models.CharField(max_length=100)),
            ],
        ),
    ]
