# Generated by Django 4.2 on 2023-05-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id_objectif', models.AutoField(primary_key=True, serialize=False)),
                ('objectif_name', models.CharField(max_length=400)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
    ]
