# Generated by Django 4.2 on 2023-05-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='names',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
