# Generated by Django 4.2 on 2023-05-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_category_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
