# Generated by Django 4.2 on 2023-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_answer_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
