# Generated by Django 4.2 on 2023-05-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_question_poid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poid',
            new_name='poids',
        ),
    ]
