# Generated by Django 4.2 on 2023-05-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_poid_question_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='commentaire',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
