# Generated by Django 4.2 on 2023-05-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userdnssi'),
        ('dashboard', '0018_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userdnssi'),
        ),
    ]
