# Generated by Django 4.2 on 2023-06-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_profil_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
