# Generated by Django 4.2 on 2023-06-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_userdnssi_email_remove_userdnssi_entite_and_more'),
        ('dashboard', '0020_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('entite', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('evaluationRecente', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userdnssi')),
            ],
        ),
    ]
